

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
spec:
  selector:
    app: postgres-app
  ports:
  - port: 5432
    targetPort: 5432

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-app
  template:
    metadata:
      labels:
        app: postgres-app
    spec:
      containers:
      - name: postgres-app
        image: postgres:15.0
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            value: "pg#123"
          - name: POSTGRES_USER
            value: "kubenews"
          - name: POSTGRES_DB
            value: "kubenews"

---
apiVersion: v1
kind: Service
metadata:
  name: kube-news-svc
spec:
  type: NodePort
  selector:
    app: kube-news-app
  ports:
  - port: 30000
    targetPort: 8080
    nodePort: 30000
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-news-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kube-news-app
  template:
    metadata:
      labels:
        app: kube-news-app
    spec:
      containers:
      - name: kube-news-app
        image: affigueiredo/kube-news:latest
        ports:
        - containerPort: 8080
        env:
          - name: DB_PASSWORD
            value: "pg#123"
          - name: DB_USERNAME
            value: "kubenews"
          - name: DB_DATABASE
            value: "kubenews"
          - name: DB_HOST
            value: "postgres-svc"